config/routes.rb
Rails.application.routes.draw do
  
  root 'gossips#index'
  
  devise_for :users

  resources :gossips

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'home/index'

  get 'users/new', to: 'users#new'

  post 'gossips/new', to: 'gossips#create'
  #get 'gossips/index'

  #get 'gossips/new'
  #post 'gossips/new'

  #get 'gossips/create'
  #post 'gossips/create'

  #get 'gossips/show'
  get 'home/warning', to: 'home#warning'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  
  belongs_to :user
  validates :content, presence: true

end

app/models/user.rb
class User < ApplicationRecord

  has_many :gossips, dependent: :destroy
  
  attr_accessor :sign_up_code
  validates :sign_up_code,
    on: :create,
    presence: true,
    inclusion: { in: ["THP2018"] }



  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :unblock_parameters, if: :devise_controller?

  def unblock_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :sign_up_code])
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
 
	def index
		@gossips = Gossip.all
	end

	def new
		@gossip = Gossip.new 
	end
	
	def create
		@gossip = Gossip.new(gossip_params)
		@gossip.user = current_user
		@gossip.save
		redirect_to gossips_path
	end

	def show
		@gossip = Gossip.find(params[:id])
	end

	def edit
		@gossip = Gossip.find(params[:id])
	end

	def update
		@gossip = Gossip.find(params[:id])
		if @gossip.update(gossip_params)
			redirect_to @gossip
		else 
			render 'edit'
		end
	end

	def destroy
		@gossip = Gossip.find(params[:id])
		@gossip.destroy
		redirect_to gossips_path
	end

	private
 	
 	def gossip_params
    	params.permit(:content)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/edit.html.erb
<% if current_user == @gossip.user %>

<h1> Editer mon gossip </h1>

<%= form_tag gossip_path(@gossip), method: :put do %>
 
<p> <%= label_tag 'content', "Votre gossip" %> </p>
<p> <%= text_area_tag 'content' %> </p>
 
<%= submit_tag "Modifier mon gossip"%>

<% end %>


<% else %>

<p> Ce n'est pas votre gossip, petit coquin ! </p>

<% end %>

<p> <%= link_to('Voir tous les gossips', gossips_path) %> </p> 

app/views/gossips/index.html.erb
<% if user_signed_in? %>

<h1> Tous nos Gossips :</h1>

<table class="table table-striped">
  <tr>
    <th>Pseudo</th>
    <th>Gossip</th>
    <th>Créé le</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @gossips.each do |gossip| %> 

    <tr>
      <td><%= gossip.user.username %></td>
      <td><%= gossip.content %></td>
      <td><%= gossip.created_at.strftime("%d-%m-%Y") %></td>
      <td><%= link_to "Voir le gossip", gossip_path(gossip) %></td>
      <% if current_user == gossip.user %>
      <td><%= link_to "Editer mon gossip", edit_gossip_path(gossip) %></td>
      <td> <%= link_to "Supprimer mon gossip", gossip_path(gossip),
              method: :delete,
              data: { confirm: 'Etes-vous sûr ?' } %> </td>
      <% else %><td></td><td></td>
      <% end %>        
    </tr>
  <% end %>
</table>

<p class = "text-center"> <%= link_to('Un nouveau gossip ?', new_gossip_path, class: "btn btn-success") %> </p> 
<p class = "text-center"> <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "btn btn-warning" %>

<% else %>

<div class="center jumbotron">
  <h1>Bienvenue à toi cher Moussaillon !</h1>
  <h3>Tu veux connaître nos derniers gossips 🎓</h3>
  <%= link_to "Pour se connecter", new_user_session_path, class: "btn btn-lg btn-primary" %>
  <%= link_to "Pour s'enregistrer", new_user_registration_path, class: "btn btn-lg btn-primary" %>
</div>

<% end %>

app/views/gossips/new.html.erb
<h1> Créer nouvel Gossip </h1>

<div class= "container">
<%= form_tag (gossips_path) do %>
 
<p> <%= label_tag 'content', "Votre gossip" %> </p>
<p> <%= text_area_tag 'content' %> </p>

<p> <%= submit_tag 'Je balance', class: "btn btn-primary"%></p>

<% end %>

<p> <%= link_to('Voir tous les gossips', gossips_path) %> </p> 

</div>

app/views/gossips/show.html.erb
<h2> Gossip by <%= @gossip.user.username %> </h2>

<p> <%= @gossip.content %> </p>

<% if current_user == @gossip.user %>

<p> <%= link_to "Editer mon gossip", edit_gossip_path %> </p> 

<% end %>

<p> <%= link_to "Voir tous les gossips", gossips_path %> </p> 

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://github.com/plataformatec/devise">Gossip_devise app</a>
    by <a href="https://github.com/nicolasroulleau">Nicolas Roulleau</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Allez", '#' %></li>
      <li><%= link_to "les", '#' %></li>
      <li><%= link_to "bleus", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "THP GOSSIPS", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        
        <% if user_signed_in? %>
          <li><%= link_to "Tous nos gossips", root_path %></li>
          <li><%= link_to "Créer mon gossip", new_gossip_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Bienvenue <%= current_user.username %> <b class="caret"></b>
            </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Modifier mon profil", edit_user_registration_path %></li>
                <li class="divider"></li>
                <li><%= link_to 'Se déconnecter', destroy_user_session_path, method: :delete %></li>
              </ul>
          </li>
        <% else %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GossipDevise</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="flash_message">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>

    <div class="header">
    <%= render 'layouts/header' %>
    </div>
    
    <div class="container">
      <%= yield %>
	  </div>
    
    <div class="footer">
    <%= render 'layouts/footer' %>
    </div>
    
  </body>
</html>